services:
    david63.acpversioncheck.listener:
        class: david63\acpversioncheck\event\listener
        arguments:
            - '@config'
            - '@template'
            - '%core.root_path%'
            - '@language'
            - '@david63.acpversioncheck.core.functions'
        tags:
            - { name: event.listener }

    david63.acpversioncheck.core.functions:
        class: david63\acpversioncheck\core\functions
        arguments:
            - '@ext.manager'
