imports:
    - { resource: alias.yml }

services:
    _defaults:
        autowire: true
        bind:
            $root_path: '%core.root_path%'
        public: true			

    david63.acpversioncheck.listener:
        class: david63\acpversioncheck\event\listener
        tags:
            - { name: event.listener }

    david63.acpversioncheck.core.functions:
        class: david63\acpversioncheck\core\functions
